import { Providers } from "./providers";
import { AppWrapper } from "../context/index";
import "./globals.css";
import { Poppins } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Product",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: "500",
  variable: "--poppins-font",
});

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  return (
    <html lang={locale} suppressHydrationWarning>
      <UserProvider>
        <body className={poppins.className}>
          <Providers>
            <AppWrapper>{children}</AppWrapper>
          </Providers>
        </body>
      </UserProvider>
    </html>
  );
}
