import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { AppWrapper } from "../context/index";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Product",
  description: "Generated by create next app",
};

// const i18nNamespace = ["header", "login"];
// interface MainProps {
//   params: {
//     locale: string | undefined;
//   };
// }

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  // const { t, resources } = await initTranslations(locale, i18nNamespace);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={` ${inter.className}`}>
        <Providers>
          <AppWrapper>{children}</AppWrapper>
        </Providers>
      </body>
    </html>
  );
}
